//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MyDBModel", "FK_meetings_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Examen3_Progra4.user), "meetings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Examen3_Progra4.meeting), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_todos_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Examen3_Progra4.user), "todos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Examen3_Progra4.todo), true)]

#endregion

namespace Examen3_Progra4
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyDBEntities object using the connection string found in the 'MyDBEntities' section of the application configuration file.
        /// </summary>
        public MyDBEntities() : base("name=MyDBEntities", "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDBEntities object.
        /// </summary>
        public MyDBEntities(string connectionString) : base(connectionString, "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDBEntities object.
        /// </summary>
        public MyDBEntities(EntityConnection connection) : base(connection, "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<meeting> meetings
        {
            get
            {
                if ((_meetings == null))
                {
                    _meetings = base.CreateObjectSet<meeting>("meetings");
                }
                return _meetings;
            }
        }
        private ObjectSet<meeting> _meetings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<todo> todos
        {
            get
            {
                if ((_todos == null))
                {
                    _todos = base.CreateObjectSet<todo>("todos");
                }
                return _todos;
            }
        }
        private ObjectSet<todo> _todos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the meetings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomeetings(meeting meeting)
        {
            base.AddObject("meetings", meeting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the todos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotodos(todo todo)
        {
            base.AddObject("todos", todo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="meeting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class meeting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new meeting object.
        /// </summary>
        /// <param name="idMeet">Initial value of the idMeet property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="fecha">Initial value of the fecha property.</param>
        /// <param name="longitud">Initial value of the longitud property.</param>
        /// <param name="latitud">Initial value of the latitud property.</param>
        /// <param name="userOwner">Initial value of the userOwner property.</param>
        public static meeting Createmeeting(global::System.Int32 idMeet, global::System.String nombre, global::System.String descripcion, global::System.DateTime fecha, global::System.Double longitud, global::System.Double latitud, global::System.String userOwner)
        {
            meeting meeting = new meeting();
            meeting.idMeet = idMeet;
            meeting.nombre = nombre;
            meeting.descripcion = descripcion;
            meeting.fecha = fecha;
            meeting.longitud = longitud;
            meeting.latitud = latitud;
            meeting.userOwner = userOwner;
            return meeting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMeet
        {
            get
            {
                return _idMeet;
            }
            set
            {
                if (_idMeet != value)
                {
                    OnidMeetChanging(value);
                    ReportPropertyChanging("idMeet");
                    _idMeet = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idMeet");
                    OnidMeetChanged();
                }
            }
        }
        private global::System.Int32 _idMeet;
        partial void OnidMeetChanging(global::System.Int32 value);
        partial void OnidMeetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double longitud
        {
            get
            {
                return _longitud;
            }
            set
            {
                OnlongitudChanging(value);
                ReportPropertyChanging("longitud");
                _longitud = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("longitud");
                OnlongitudChanged();
            }
        }
        private global::System.Double _longitud;
        partial void OnlongitudChanging(global::System.Double value);
        partial void OnlongitudChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double latitud
        {
            get
            {
                return _latitud;
            }
            set
            {
                OnlatitudChanging(value);
                ReportPropertyChanging("latitud");
                _latitud = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("latitud");
                OnlatitudChanged();
            }
        }
        private global::System.Double _latitud;
        partial void OnlatitudChanging(global::System.Double value);
        partial void OnlatitudChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userOwner
        {
            get
            {
                return _userOwner;
            }
            set
            {
                OnuserOwnerChanging(value);
                ReportPropertyChanging("userOwner");
                _userOwner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userOwner");
                OnuserOwnerChanged();
            }
        }
        private global::System.String _userOwner;
        partial void OnuserOwnerChanging(global::System.String value);
        partial void OnuserOwnerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_meetings_users", "users")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("MyDBModel.FK_meetings_users", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("MyDBModel.FK_meetings_users", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("MyDBModel.FK_meetings_users", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("MyDBModel.FK_meetings_users", "users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="todo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class todo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new todo object.
        /// </summary>
        /// <param name="idTodo">Initial value of the idTodo property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="fechaI">Initial value of the fechaI property.</param>
        /// <param name="fechaF">Initial value of the fechaF property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="userOwner">Initial value of the userOwner property.</param>
        public static todo Createtodo(global::System.Int32 idTodo, global::System.String nombre, global::System.String descripcion, global::System.DateTime fechaI, global::System.DateTime fechaF, global::System.String status, global::System.String userOwner)
        {
            todo todo = new todo();
            todo.idTodo = idTodo;
            todo.nombre = nombre;
            todo.descripcion = descripcion;
            todo.fechaI = fechaI;
            todo.fechaF = fechaF;
            todo.status = status;
            todo.userOwner = userOwner;
            return todo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTodo
        {
            get
            {
                return _idTodo;
            }
            set
            {
                if (_idTodo != value)
                {
                    OnidTodoChanging(value);
                    ReportPropertyChanging("idTodo");
                    _idTodo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTodo");
                    OnidTodoChanged();
                }
            }
        }
        private global::System.Int32 _idTodo;
        partial void OnidTodoChanging(global::System.Int32 value);
        partial void OnidTodoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaI
        {
            get
            {
                return _fechaI;
            }
            set
            {
                OnfechaIChanging(value);
                ReportPropertyChanging("fechaI");
                _fechaI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaI");
                OnfechaIChanged();
            }
        }
        private global::System.DateTime _fechaI;
        partial void OnfechaIChanging(global::System.DateTime value);
        partial void OnfechaIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaF
        {
            get
            {
                return _fechaF;
            }
            set
            {
                OnfechaFChanging(value);
                ReportPropertyChanging("fechaF");
                _fechaF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaF");
                OnfechaFChanged();
            }
        }
        private global::System.DateTime _fechaF;
        partial void OnfechaFChanging(global::System.DateTime value);
        partial void OnfechaFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userOwner
        {
            get
            {
                return _userOwner;
            }
            set
            {
                OnuserOwnerChanging(value);
                ReportPropertyChanging("userOwner");
                _userOwner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userOwner");
                OnuserOwnerChanged();
            }
        }
        private global::System.String _userOwner;
        partial void OnuserOwnerChanging(global::System.String value);
        partial void OnuserOwnerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_todos_users", "users")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("MyDBModel.FK_todos_users", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("MyDBModel.FK_todos_users", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("MyDBModel.FK_todos_users", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("MyDBModel.FK_todos_users", "users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static user Createuser(global::System.String email, global::System.String password)
        {
            user user = new user();
            user.email = email;
            user.password = password;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                if (_email != value)
                {
                    OnemailChanging(value);
                    ReportPropertyChanging("email");
                    _email = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("email");
                    OnemailChanged();
                }
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_meetings_users", "meetings")]
        public EntityCollection<meeting> meetings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<meeting>("MyDBModel.FK_meetings_users", "meetings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<meeting>("MyDBModel.FK_meetings_users", "meetings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_todos_users", "todos")]
        public EntityCollection<todo> todos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<todo>("MyDBModel.FK_todos_users", "todos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<todo>("MyDBModel.FK_todos_users", "todos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
